quartiq/minimq

src/ser/packet_writer.rs
This PR fixes #7 by correcting the encoding for variable length integers. The order was previously reversed.
Testing:
* An MQTT publish packet was generated with a size of 386. It was confirmed that the packet was properly digested by the broker.
=> Fixing variable length integer encoding

Cargo.toml, src/mqtt_client.rs, tests/integration_test.rs
This PR fixes #9 by removing the embedded-nal github reference in favor of the crates.io version to allow for publishing.
=> Updating embedded-nal dependency

CHANGELOG.md, src/mqtt_client.rs
This PR updates the internal `poll()` closure argument to be a `FnMut` to allow state mutation.
This fixes #16 
Changes have been tested with an MQTT client embedded on a real device mutating state in response to subscribed topic messages.
This PR also adds in a changelog markdown file for tracking repository changes.
=> Updating poll closure to be mutable

src/mqtt_client.rs, tests/integration_test.rs
This PR fixes #19 by updating the `publish()` function to check if a connection with the broker exists before sending a message.
=> Updating is_connected() function

CHANGELOG.md, examples/minimq-stm32h7/Cargo.lock, src/mqtt_client.rs
This PR removes the `nb::block!()` during read requests to prevent inadvertent blocking. Instead, the read request returns 0, indicating no data read.
This also propagates a network error out of MiniMQ and removes an unwrap.
This fixes #25
=> Updating nb result handling

CHANGELOG.md, Cargo.toml
This PR stages the 0.2.0 release of `minimq`
=> Preparing for 0.2.0 release

src/mqtt_client.rs
This PR fixes #38 by replacing the nb::block!() call with an error mapping to `Error::WriteFail`, as blocking may never complete (e.g. for network stacks like smoltcp that need software processing of ingress/egress).
=> Removing blocking write

CHANGELOG.md, Cargo.toml, src/mqtt_client.rs
This PR fixes #28 by refactoring state management within `minimq` to properly track various connection state details. Notably, now, after an active connection is lost, `minimq` will `close()` the current socket so that the transmit portion of the socket also closes. This was previously holding up (re)connection attempts, as the socket was still partially connected.
This PR unifies all of the connection state management into a logical sequence of steps.
TODO:
=> Refactoring state management

CHANGELOG.md, Cargo.toml, tests/integration_test.rs
This is doing b0b60b2e again after 2f4dd69f reintroduced a local version
due to std-embedded-nal lagging behind embedded-nal development.
---
Thanks to your [PR](https://gitlab.com/chrysn/std-embedded-nal/-/merge_requests/2), std-embedded-nal is again at state-of-the-art embedded-nal level.
Alternatively to this, if std-embedded-nal is too slow to adapt, it should probably be removed from dev-dependencies.
(As an alternative to the alternative, given that maintaining the code removed here is very similar to the steps in maintaining std-embedded-nal, I'd be happy to invite you to become comaintainer of that crate).
=> Replace ad-hoc std-based NAL with std-embedded-nal

CHANGELOG.md, Cargo.toml, README.md, src/de/deserialize.rs, src/mqtt_client.rs, src/ser/serialize.rs, src/session_state.rs, tests/integration_test.rs
This PR refactors #36 after a restructure of `minimq` and implements ping request/response support.
This PR fixes #51 
The integraton test was modified to never exit and I monitored network traffic on the loopback. I observed the ping request/response at the expected 30s interval on wireshark.
=> Adding keep-alive support

CHANGELOG.md, Cargo.toml, src/lib.rs, tests/integration_test.rs
This PR updates the tests to use `std-embedded-time` and updates the documentation in `lib.rs` to be compiled so that it doesn't become stale. It previously was broken.
This PR fixes #49
=> Updating dependencies and docs

CHANGELOG.md, src/de/deserialize.rs, src/de/packet_reader.rs, src/lib.rs, src/mqtt_client.rs, src/network_manager.rs, src/properties.rs, src/ser/serialize.rs
This PR refactors the network stack / network socket management into a separate structure. This addresses borrow-checker/ownership semantic issues that arise when trying to write control packets that are buffered internally in minimq (e.g. QoS > 0). Specifically, this is resolved because `MqttClient` no longer needs to be borrowed to write the packet, as you can now borrow the `InterfaceHolder` directly for writes.
This addresses issues identified in https://github.com/quartiq/minimq/pull/57
CC @mladedav
=> Refactoring network stack management into holder class

CHANGELOG.md, src/lib.rs, src/mqtt_client.rs, src/ser/packet_writer.rs, src/ser/serialize.rs, src/will.rs, tests/integration_test.rs
This PR adds support for sending a `Will` message in the connection request to the broker.
The will is a message that will be published whenever the client disconnects without explicitly sending a `Disconnect` message.
This can be used to allow the broker to report, for example, the connection state of a client.
=> Adding support for will messages

CHANGELOG.md, Cargo.toml, src/mqtt_client.rs, src/session_state.rs, tests/integration_test.rs
This PR fixes #69 by adjusting state management that is used to determine when keepalive intervals may be configured.
This PR also fixes #70 by properly dividing by 1000 instead of multiplying when retrieving the keepalive.
I applied this patch to an active stabilizer, waited for `alive` topics to be published by `miniconf`, and then disconnected ethernet. After 2.5 minutes the `alive` topic will properly indicated that the device was no longer connected.
=> Patching keepalive interval support

CHANGELOG.md, src/lib.rs, src/mqtt_client.rs, src/network_manager.rs
This PR fixes #74 by incorporating changes from #68 with additional safeguards.
Specifically, any attempt to write a packet is now safe guarded by checking that packet writes are acceptable. It's invalid to attempt to send a packet while a partial packet is still being transmitted, as this would corrupt the MQTT connection.
CC @mladedav
=> Handling partial MQTT packet writes

src/lib.rs, src/mqtt_client.rs, src/network_manager.rs
I've been running into issues with getting RST packets from brokers fairly often if there was high load. This is painful especially because starting the connection takes really long time for some reason. It turns out my TCP stack just couldn't keep up and in the current implementation the `WriteFail` error is returned if the write would either block or if it was partially written. The latter usually breaks the MQTT connection because there is currently no way to finish the packet send.
The issue is with the partial writes which usually contained the header including length of the MQTT message but only the first half was actually transferred, the rest was silently dropped. On a subsequent write the first half of the next packet would be interpreted by the broker as the second half of the …
=> Implement finishing partial writes

CHANGELOG.md, src/lib.rs
This PR fixes #72 by making the `mqtt_client` module public.
(thanks @systec-ms!)
=> Correcting documentation generation

src/network_manager.rs
This PR fixes #76 by handling `nb::WouldBlock` errors to instead buffer the outbound packet. This preserves any MQTT state transitions.
=> Handling WouldBlock errors on network send

CHANGELOG.md, Cargo.toml
This PR prepares for release of minimq 0.5.2, which includes patches so that partial packet writes don't break the broker connection.
=> Preparing for 0.5.2

CHANGELOG.md, src/properties.rs
This PR fixes the `Property` enum to derive PartialEq to allow easy comparison of properties. This is useful e.g. for comparing CorrelationData.
=> Deriving PartialEq for properties

CHANGELOG.md, src/lib.rs, src/mqtt_client.rs, src/session_state.rs
This PR adds the possibility to set custom target port numbers deviating from 1883.
=> Allow configuration of non default port

CHANGELOG.md, src/mqtt_client.rs, src/session_state.rs
This PR refactors the state management of the client to be entirely wrapped up in an `smlang::StateMachine`.
This change is intended to support more complex state management that will be required to support all QoS levels.
This PR also removes public access to the `Minimq.client` object. It is now exposed via `Minimq::client()` to support compatibility going forward.
=> Refactoring MQTT state management

CHANGELOG.md, src/lib.rs, src/mqtt_client.rs, src/session_state.rs
This PR fixes #59 by guaranteeing that all QoS retransmissions will be properly republished upon reconnecting to the broker.
=> Implementing robust QoS retransmission

CHANGELOG.md, Cargo.toml, README.md, src/de/deserialize.rs, src/de/packet_reader.rs, src/lib.rs, src/mqtt_client.rs, src/network_manager.rs, src/ser/serialize.rs, src/session_state.rs, tests/exactly_once_transmission.rs
This PR adds support for the `QoS::ExactlyOnce` transmission mechanism.
This PR fixes #60 
This PR builds on #90 
TODO:
=> Adding `Qos::ExactlyOnce` transmission support

CHANGELOG.md, src/de/deserialize.rs, src/de/mod.rs, src/de/packet_parser.rs, src/de/packet_reader.rs, src/mqtt_client.rs, src/properties.rs, src/ser/serialize.rs
This PR refactors the packet reception mechanism in Minimq to receive directly from the network stack into the `PacketReader`. The `PacketParser` has been broken off the `PacketReader` in anticipation of deserialization refactoring in the future.
This avoids one copy of the MQTT packet from the receive buffer into the packet reader.
Additionally, this PR updates it so that only a single MQTT packet is read from the network per `poll()` execution at most, which paves the way for fixing #80.
=> Updating parsing to avoid copying

CHANGELOG.md, src/mqtt_client.rs, tests/poll_result.rs
This PR fixes #80 by adding support for returning data from `poll()`'s closure. This can be used to propogate behavior to the higher level without using mutable state.
=> Adding support for returning results from poll closures

CHANGELOG.md, Cargo.toml, src/de/packet_parser.rs, src/properties.rs, src/ser/packet_writer.rs, src/ser/serialize.rs, src/will.rs
This PR updates `minimq` to leverage `varint-rs` to handle varint encoding and decoding.
It also removes some unnecessary boilerplate code in the property module to simplify how we serialize data.
Varints have been changed from `usize` to `u32`.
=> Leveraging external tools for variable length integers

CHANGELOG.md, src/de/packet_reader.rs, src/mqtt_client.rs, tests/exactly_once_transmission.rs, tests/integration_test.rs, tests/poll_result.rs
This PR updates the functionality of `poll()`. Users are now informed that they should call it repeatedly until it returns `Ok(None)`. Functionality has changed such that `poll()` will process as many MQTT control packets as possible until a `publish` message is received.
This PR fixes #102
=> Refactoring `poll()` usage

CHANGELOG.md, src/de/received_packet.rs, src/design_parameters.rs, src/lib.rs, src/mqtt_client.rs, src/packets.rs, src/types.rs, tests/integration_test.rs, tests/poll_result.rs
This PR fixes #98 by allowing for a list of `TopicFilter` objects to be provided to the `subscribe()` function. Each `TopicFilter` is composed of `SubscriptionOptions` and an `topic` path. Convenience `From<&str>` has been implemented for `TopicFilter` to allow the user to subscribe similar to the previous API.
@jordens There's some nuance in allowing the user to specify multiple TopicFilters per subscription request that ripples through the codebase. Let me know what you think about the change. We don't have to support multiple `TopicFilter`s per `SUBSCRIBE` if we don't want to.
=> Refactoring subscription API

CHANGELOG.md, src/lib.rs, src/mqtt_client.rs, src/reply_options.rs, tests/integration_test.rs
This PR takes out the dirty work of managing replying to an inbound message.
There is now a convenience `reply()` API that can be used. A new `ReplyOptions` can be constructed based on the received message properties and can be further used to customize `reply()` behavior, such as ignoring cases where there is no `ResponseTopic` or using a default `ResponseTopic` when none is found.
This PR fixes #84.
=> Adding support for simply replying to inbound messages

CHANGELOG.md, README.md, src/de/deserializer.rs, src/de/mod.rs, src/de/received_packet.rs, src/lib.rs, src/mqtt_client.rs, src/packets.rs, src/reply_options.rs, src/types.rs, src/will.rs, tests/at_least_once_subscription.rs, tests/integration_test.rs
This PR adds support for subscribing at `AtLeastOnce` QoS levels.
This PR addresses parts of https://github.com/quartiq/minimq/issues/62.
This PR also refactors the way in which properties are received. Instead of receiving and deserializing all properties immediately, the binary block of properties is instead read and deserialization is deferred until later. This allows the implementation to receive arbitrary numbers of properties.
=> Adding `QoS::AtLeastOnce` subscription support, updating property management

src/de/received_packet.rs, src/lib.rs, src/mqtt_client.rs, src/packets.rs
This PR removes the arbitrary restriction on the maximum number of topics per subscription by instead just taking a slice to the subscription reason codes. These codes are then processed individually in the handler instead of being converted into ReasonCodes and pushed into a slice.
=> Removing arbitrary limit on subscription topic count

CHANGELOG.md, src/de/received_packet.rs, src/packets.rs
This PR fixes #115 by adjusting the deserialization and serialization of `PubAck` messages that have no properties.
=> Fixing handling of puback property de/serialization

CHANGELOG.md, Cargo.toml
This PR prepares for a 0.6.2 release to patch up an issue with UserProperty serialization
=> Preparing for a 0.6.2 release

CHANGELOG.md, Cargo.toml
Preps for a 0.7.0 release of minimq so we can deploy connectivity fixes.
=> Preparing for 0.7 release

src/de/packet_reader.rs, src/lib.rs, src/message_types.rs, src/mqtt_client.rs, src/network_manager.rs, src/packets.rs, src/ser/mod.rs, src/will.rs, tests/at_least_once_subscription.rs, tests/exactly_once_subscription.rs, tests/exactly_once_transmission.rs, tests/integration_test.rs, tests/poll_result.rs
This is a first stab at updating minimq to remove const generics and take the smoltcp path of user-supplied buffers. This should drastically cut down on stack and RAM usage for end users.
Fixes #112
=> Using user-supplied RX and TX buffers, removing const-generics

CHANGELOG.md, src/broker.rs, src/lib.rs, src/mqtt_client.rs, tests/at_least_once_subscription.rs, tests/exactly_once_subscription.rs, tests/exactly_once_transmission.rs, tests/integration_test.rs, tests/poll_result.rs, tests/reconnection.rs
Adds support for using brokers by domain name.
Fixes #120 
TODO:
cc @jordens
=> Adding support for domain-named brokers

CHANGELOG.md, src/mqtt_client.rs
Fixes #136 by allowing auto-downgrade of publications to the max QoS supported by the server if desired.
=> Adding support for server maximum QoS

CHANGELOG.md, src/config.rs, src/lib.rs, src/mqtt_client.rs, tests/at_least_once_subscription.rs, tests/exactly_once_subscription.rs, tests/exactly_once_transmission.rs, tests/integration_test.rs, tests/poll_result.rs, tests/reconnection.rs
This PR refactors the setup of the Minimq client into a single `Config` struct. This removes the need to do run-time checks on the client state and makes it simpler to see which buffers are being used for what. It also cuts down on the number of arguments needed in `Minimq::new()`
=> Refactoring configuration to builder semantics

src/config.rs, src/mqtt_client.rs, src/packets.rs, src/ser/mod.rs, src/will.rs, tests/integration_test.rs, tests/stack/mod.rs
This PR refactors the `will` temporary storage such that the `will` is serialized at configuration time into a user-provided buffer. This means that the `Will` message itself does not need to live very long.
Pros and Cons:
* User has to provide yet another buffer at config time
* Libraries can leverage will memory provided by the user to construct customized wills.
* Will serialization only ever happens once
=> Updating will management

CHANGELOG.md, src/config.rs, src/de/received_packet.rs, src/lib.rs, src/message_types.rs, src/mqtt_client.rs, src/network_manager.rs, src/packets.rs, src/publication.rs, src/ser/mod.rs, src/types.rs, src/varint.rs, tests/deferred_payload.rs, tests/stack/mod.rs
This PR is designed to allow an end user to provide a `Publication` message with a yet-to-be-serialized payload. This then allows them to serialize their payload _directly_ into the MQTT TX buffer, which eliminates the need for them serializing and then copying it over into the MQTT payload.
Example:
```rs
client.publish(Publication::new_deferred(|buf| settings.get(key, buf)));
```
=> Refactoring publication to support zero-copy serialization

src/config.rs, src/lib.rs, src/packets.rs, src/will.rs
Updating the will to be a bit more usable with builder semantics. Ref https://github.com/quartiq/miniconf/pull/179#discussion_r1311439931
Also flagging an attempt to assign multiple wills as an error. This would potentially just lose allocated memory.
=> Updating will to use builder semantics

src/network_manager.rs
This PR fixes an issue I encountered with pending writes when integrating miniconf/minimq onto Stabilizer.
The cached pending write needs to use the `start` and `len` parameters when refreshing the cache indices, otherwise we accidentally cause malformed packets due to incorrect indices.
=> Fixing pending write cache management

Cargo.toml, src/mqtt_client.rs, src/packets.rs, src/types.rs
Add a set_auth function to set the user name and password. I test with the version 0.7.0 and it works fine. Not sure if it compatible with the current version.
[issue 119](https://github.com/quartiq/minimq/issues/119)
Fixes #119
=> Adding support for authentication

src/config.rs, src/lib.rs, src/mqtt_client.rs, src/packets.rs, src/types.rs
This PR updates auth to:
1. Use the `ConfigBuilder` struct for specification to align with other start-up behaviors
2. Uses the `buffer` from the config to back the memory needed to cache the auth credentials, eliminating the need for heapless::String types (which impose run-time cost on users that don't need auth)
3. Excludes auth serialization without the expected feature flag to prevent accidentally providing insecure credentials.
CC @cnmozzie
=> Refactoring auth data to not use heapless Strings, fixing build

src/mqtt_client.rs, src/network_manager.rs, src/packets.rs, src/publication.rs, src/ser/mod.rs, tests/at_least_once_subscription.rs, tests/exactly_once_subscription.rs
The `DeferredPayload` needs to be `FnOnce` (or `FnMut`) if we want the user to be able to mutate data within a deferred payload calculation.
This is necessary for things like i.e. `minireq`, where the user is going to be doing application-level logic within a `DeferredPayload` calculation, which may necessitate mutation of data and context.
I also implemented `ToPayload` for `&str` so you can now call `Publication::new("Hello")` without having to call `as_bytes()` on the str.
=> Elevating ToPayload to FnOnce, adding ToPayload for &str

Cargo.toml
- bump std-embedded-nal to v0.2
- bump outdated deps
=> rj/std embedded nal 0.2

CHANGELOG.md, src/de/packet_reader.rs
Prevents a panic in `fn receive_buffer` if a packet with a too big length is received.
=> Handle bad length in header

src/broker.rs, src/config.rs, src/message_types.rs, src/mqtt_client.rs, src/packets.rs, src/publication.rs, src/varint.rs
=> Simplifying struct bounds

CHANGELOG.md, src/lib.rs, src/mqtt_client.rs, src/packets.rs, src/publication.rs, tests/at_least_once_subscription.rs, tests/deferred_payload.rs, tests/exactly_once_subscription.rs, tests/exactly_once_transmission.rs, tests/integration_test.rs, tests/poll_result.rs, tests/reconnection.rs
Fixes #159 by refactoring the `Publication` API to avoid forcing an `unwrap()` on all users, and instead moves the `unwrap()` to a new `Publication::respond` API for constructing a new publication.
Users that have a predefined topic no longer need to unnecessarily unwrap or call `finish()` at all.
=> Removing results from Publication API
